[book]
title = "Arbitrum Foundations"
authors = ["buidlabz"]
description = "The book is an intro to start building on Arbitrum"
language = "en"
multilingual = false
src = "src"
text-direction= "ltr"

[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
additional-css = ["general.css"]
additional-js = ["custom.js"]
site-url = "https://metameta-club.github.io/Foundations/"
git-repository-url = "https://github.com/MetaMeta-Club/Foundations"
git-repository-icon = "fa-github"